[package]
name = "http-collator"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
dashmap.workspace = true
h2session.workspace = true
http.workspace = true
httparse.workspace = true
